[package]
name = "guardit"
version = "0.3.0"
edition = "2024"
license = "MIT"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
ratatui = { version = "0.30", default-features = false, features = ["crossterm", "layout-cache", "underline-color", "macros"] }
crossterm = "0.29"
nfq = "0.2.5"
serde_json = "1.0.151"
libc = "0.2.189"
clap_complete = "4"
clap_mangen = "0.3"

[profile.release]
strip = true
